pianostore/urls.py
#from django
from django.conf.urls.defaults import *

# from pianostore
#from models import Track

urlpatterns = patterns('pianostore.views',
        url(r'^$', 'tracks', name="all_tracks"),
        url(r'^(\d+)/track/$', 'track', name="describe_track"),
        url(r'^your_tracks/$', 'your_tracks', name="your_tracks"),
        url(r'^user_tracks/(?P<username>\w+)/$', 'user_tracks',
            name="user_tracks"),
        # CRUD urls
        url(r'^add/$', 'add_track', name="add_track"),
        url(r'^(\d+)/update/$', 'update_track',
            name="update_track"),
        url(r'^(\d+)/delete/$', 'delete_track',
            name="delete_track"),
        url(r"^upload_progress/$", "upload_progress", name="upload_progress"),
    )

urls.py
# from django
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.contrib.sitemaps import GenericSitemap
#from django.contrib.sitemaps import FlatPageSitemap

from django.contrib import admin
admin.autodiscover()

# from pinax
from bookmarks.feeds import BookmarkFeed
from bookmarks.models import BookmarkInstance
from microblogging.feeds import TweetFeedAll, TweetFeedUser, TweetFeedUserWithFriends
from microblogging.models import Tweet
from swaps.models import Offer
from tagging.models import TaggedItem
from wakawaka.models import WikiPage

from pinax.apps.account.openid_consumer import PinaxConsumer
from pinax.apps.blog.feeds import BlogFeedAll, BlogFeedUser
from pinax.apps.blog.models import Post
from pinax.apps.photos.models import Image
from pinax.apps.topics.models import Topic
from pinax.apps.tribes.models import Tribe

# from internal apps
from pianostore.sitemap import TrackSitemap

handler500 = "pinax.views.server_error"


# Feeds
tweets_feed_dict = {"feed_dict": {
    "all": TweetFeedAll,
    "only": TweetFeedUser,
    "with_friends": TweetFeedUserWithFriends,
}}
blogs_feed_dict = {"feed_dict": {
    "all": BlogFeedAll,
    "only": BlogFeedUser,
}}
bookmarks_feed_dict = {"feed_dict": {"": BookmarkFeed }}


# Sitemaps
blog_info_dict = {
    'queryset': Post.objects.all(),
    'date_field': 'updated_at',
}
sitemaps = {
        #'flatpages': FlatPageSitemap,
        'blog': GenericSitemap(blog_info_dict, priority=0.6, changefreq='daily'),
        'pianostore': TrackSitemap,
}


urlpatterns = patterns("",
    url(r"^$", direct_to_template, {
        "template": "homepage.html",
    } ,name="home"),
    url(r"^admin/invite_user/$", "pinax.apps.signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^about/", include("about.urls")),
    url(r"^account/", include("pinax.apps.account.urls")),
    url(r"^openid/(.*)", PinaxConsumer()),
    url(r"^profiles/", include("pinax.apps.profiles.urls")),
    url(r"^bbauth/", include("pinax.apps.bbauth.urls")),
    url(r"^authsub/", include("pinax.apps.authsub.urls")),
    url(r"^blog/", include("pinax.apps.blog.urls")),
    url(r"^invitations/", include("friends_app.urls")),
    url(r"^notices/", include("notification.urls")),
    url(r"^messages/", include("messages.urls")),
    url(r"^announcements/", include("announcements.urls")),
    url(r"^tweets/", include("microblogging.urls")),
    url(r"^tribes/", include("pinax.apps.tribes.urls")),
    url(r"^comments/", include("threadedcomments.urls")),
    url(r"^i18n/", include("django.conf.urls.i18n")),
    url(r"^bookmarks/", include("bookmarks.urls")),
    url(r"^photos/", include("pinax.apps.photos.urls")),
    url(r"^avatar/", include("avatar.urls")),
    url(r"^swaps/", include("swaps.urls")),
    url(r"^flag/", include("flag.urls")),
    url(r"^locations/", include("locations.urls")),
    url(r"^feeds/tweets/(.*)/$", "django.contrib.syndication.views.feed", tweets_feed_dict),
    url(r"^feeds/posts/(.*)/$", "django.contrib.syndication.views.feed", blogs_feed_dict),
    url(r"^feeds/bookmarks/(.*)/?$", "django.contrib.syndication.views.feed", bookmarks_feed_dict),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.index', {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r"^pianostore/", include("pianostore.urls")),
)

## @@@ for now, we'll use friends_app to glue this stuff together

friends_photos_kwargs = {
    "template_name": "photos/friends_photos.html",
    "friends_objects_function": lambda users: Image.objects.filter(is_public=True, member__in=users),
}

friends_blogs_kwargs = {
    "template_name": "blog/friends_posts.html",
    "friends_objects_function": lambda users: Post.objects.filter(author__in=users),
}

friends_tweets_kwargs = {
    "template_name": "microblogging/friends_tweets.html",
    "friends_objects_function": lambda users: Tweet.objects.filter(sender_id__in=[user.id for user in users], sender_type__name="user"),
}

friends_bookmarks_kwargs = {
    "template_name": "bookmarks/friends_bookmarks.html",
    "friends_objects_function": lambda users: Bookmark.objects.filter(saved_instances__user__in=users),
    "extra_context": {
        "user_bookmarks": lambda request: Bookmark.objects.filter(saved_instances__user=request.user),
    },
}

urlpatterns += patterns("",
    url(r"^photos/friends_photos/$", "friends_app.views.friends_objects", kwargs=friends_photos_kwargs, name="friends_photos"),
    url(r"^blog/friends_blogs/$", "friends_app.views.friends_objects", kwargs=friends_blogs_kwargs, name="friends_blogs"),
    url(r"^tweets/friends_tweets/$", "friends_app.views.friends_objects", kwargs=friends_tweets_kwargs, name="friends_tweets"),
    url(r"^bookmarks/friends_bookmarks/$", "friends_app.views.friends_objects", kwargs=friends_bookmarks_kwargs, name="friends_bookmarks"),
)

tagged_models = (
    dict(title="Blog Posts",
        query=lambda tag : TaggedItem.objects.get_by_model(Post, tag).filter(status=2),
        content_template="pinax_tagging_ext/blogs.html",
    ),
    dict(title="Bookmarks",
        query=lambda tag : TaggedItem.objects.get_by_model(BookmarkInstance, tag),
        content_template="pinax_tagging_ext/bookmarks.html",
    ),
    dict(title="Photos",
        query=lambda tag: TaggedItem.objects.get_by_model(Image, tag).filter(safetylevel=1),
        content_template="pinax_tagging_ext/photos.html",
    ),
    dict(title="Swap Offers",
        query=lambda tag : TaggedItem.objects.get_by_model(Offer, tag),
    ),
    dict(title="Topics",
        query=lambda tag: TaggedItem.objects.get_by_model(Topic, tag),
    ),
    dict(title="Tribes",
        query=lambda tag: TaggedItem.objects.get_by_model(Tribe, tag),
    ),
    dict(title="Wiki Articles",
        query=lambda tag: TaggedItem.objects.get_by_model(WikiPage, tag),
    ),
)
tagging_ext_kwargs = {
    "tagged_models": tagged_models,
}

urlpatterns += patterns("",
    url(r"^tags/(?P<tag>.+)/(?P<model>.+)$", "tagging_ext.views.tag_by_model",
        kwargs=tagging_ext_kwargs, name="tagging_ext_tag_by_model"),
    url(r"^tags/(?P<tag>.+)/$", "tagging_ext.views.tag",
        kwargs=tagging_ext_kwargs, name="tagging_ext_tag"),
    url(r"^tags/$", "tagging_ext.views.index", name="tagging_ext_index"),
)

if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
    )

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^translation/', include('rosetta.urls')),
    )

pianostore/models.py
#!/usr/bin/python
# -*- coding:Utf-8 -*-

'''
File: models.py
Author: Adrien Lemaire
Description: Models for the piano app
'''

#python
from os import path
import datetime

# django
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

# from apps
from photologue.models import Photo
try:
    """ attempt to load the django-tagging TagField from default location,
    otherwise we substitude a dummy TagField. """
    from tagging.fields import TagField
    tagfield_help_text = _('Separate tags with spaces, put quotes around multiple-word tags.')
except ImportError:
    class TagField(models.CharField):
        def __init__(self, **kwargs):
            default_kwargs = {'max_length': 255, 'blank': True}
            default_kwargs.update(kwargs)
            super(TagField, self).__init__(**default_kwargs)
        def get_internal_type(self):
            return 'CharField'
    tagfield_help_text = _('Django-tagging was not found, tags will be treated as plain text.')



#class TrackManager(models.Manager):
    #"""" The track can be a video (various formats) or a audio file. """


class Track(models.Model):
    """Track Model"""

    # Videos / Images
    original_track = models.FileField(_('original track'), upload_to='pianostore/uploads/')
    track_mp4 = models.FileField(_('track.mp4'), upload_to='pianostore/mp4/')
    track_webm = models.FileField(_('track.webm'), upload_to='pianostore/webm/')
    track_ogv = models.FileField(_('track.ogv'), upload_to='pianostore/ogv/')
    image = models.ForeignKey(Photo, blank=True, null=True,
                             help_text=_('A cover image to represent this track'))

    # Texts
    title = models.CharField(_('title'), max_length=255)
    title_slug = models.SlugField('slug', unique=True,
        help_text=_('A "slug" is a unique URL-friendly title for an object.'))
    description = models.TextField(_('description'), blank=True)

    # Names
    artist = models.CharField(_('artist'), max_length=255)
    composer = models.CharField(_('composer'), max_length=255)
    adder = models.ForeignKey(User, related_name="added_tracks",
                              verbose_name=_('adder'))

    # Dates
    date_composition = models.DateTimeField(
        _('date of composition'), blank=True, null=True)
    date_added = models.DateTimeField(
        _('added'), default=datetime.datetime.now)
    #date_updated = models.DateTimeField(_('added'), default=datetime.datetime.now)

    # Other
    is_public = models.BooleanField('is public', default=True,
        help_text=_('Public videos will be displayed in the default views.'))
    category = models.CharField(_('category'), max_length=255, blank=True)
    tags = TagField(help_text=tagfield_help_text, verbose_name=_('tags'))
    #stars = models.IntegerField(_('stars'))

    def get_absolute_url(self):
        return ("describe_track", [self.pk])
    get_absolute_url = models.permalink(get_absolute_url)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.__unicode__()

    class Meta:
        ordering = ('-date_added', )
        get_latest_by = 'date_added'
        verbose_name = "track"
        verbose_name_plural = "tracks"

    def save(self, force_insert=False, force_update=False):
        super(Track, self).save(force_insert, force_update)
        if settings.DEBUG:
            try:
                ping_google()
            except Exception:
                pass

    def fullpicture(self):
        """ Get full picture <a>. """
        if self.image:
            link = "%s" % self.image.image.url
            return '<img src=%s />' % (link)
    fullpicture.allow_tags = True

    def _get_thumb_url(self, folder, size):
        """ get a thumbnail giver a folder and a size. """
        if not self.image:
            return
        upload_to = path.dirname(self.image.image.path)
        tiny = path.join(upload_to, folder, path.basename(self.image.image.path))
        tiny = path.normpath(tiny)
        if not path.exists(tiny):
            import Image
            im = Image.open(self.image.image.path)
            im.thumbnail(size, Image.ANTIALIAS)
            im.save(tiny, 'JPEG')
        return path.join(path.dirname(self.image.image.url), folder,
                         path.basename(self.image.image.path)).replace('\\', '/')

    def get_thumb_url(self):
        return self._get_thumb_url('thumb_100_100', (100, 100))

    def thumb(self):
        """ Get thumb <a>. """
        link = self.get_thumb_url()
        if link:
            return '<img src=%s />' % (link)
    thumb.allow_tags = True

pianostore/forms.py
#from django
from django import forms
from django.utils.translation import ugettext_lazy as _

#from piano
from models import Track


class TrackForm(forms.ModelForm):
    """ Track Form: form associated to the Track model """
    rotation = forms.IntegerField(
        max_value="180",
        help_text=_("Rotation to apply on the video"))

    class Meta:
        model = Track
        #fields = ('coverart', 'composer', 'artist', 'category',
                  #'description', 'title')
        exclude = ('adder', 'track_mp4', 'track_webm', 'track_ogv',
                   'date_added')

    def __init__(self, user=None, *args, **kwargs):
        super(TrackForm, self).__init__(*args, **kwargs)
        self.user = user
        # original_track will be modified by nginx upload module
        self.fields['original_track'].required = False
        # new field rotation which will be used by celeryd
        rotation = self.fields.keyOrder.pop(
            self.fields.keyOrder.index("rotation")
        )
        self.fields.keyOrder.insert(
            self.fields.keyOrder.index("title"), rotation
        )
        self.is_update = False
        self.fields['rotation'].required = False

    def clean(self):
        """ Do validation stuff. """
        # if a track with that title already exists...
        if not self.is_update:
            if Track.objects.filter(title=self.cleaned_data['title'])\
                    .count() > 0:
                raise forms.ValidationError(_("There is already a track "
                                "with the same title in the pianostore."))
            if Track.objects.filter(original_track=self.cleaned_data['original_track'])\
                    .count() > 0:
                raise forms.ValidationError(_("There is already a track "
                                "with the same file name in the pianostore."))
        return self.cleaned_data

pianostore/templates/pianostore/add.html
{% extends "pianostore/base.html" %}

{% load i18n %}
{% load uni_form_tags %}

{% block head_title %}{% blocktrans %}Add Track{% endblocktrans %}{% endblock %}


{% block extra_body_base %}
    {{ block.super }}
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.uploadProgress.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}pianostore/js/jQueryRotate.js"></script>
    <script type="text/javascript" charset="utf-8">
    //<![CDATA[
    /*$(document).ready(function() {
        $(function() {
            $('#upload_form').uploadProgress({
            jqueryPath: "{{ STATIC_URL }}pinax/js/jquery-1.3.2.min.js",
                progressBar: '#progress_indicator',
                progressUrl: '{% url upload_progress %}',
                start: function() {
                    $("#upload_form").hide();
                    filename = $("#id_file").val().split(/[\/\\]/).pop();
                    $("#progress_filename").html('Uploading ' + filename + "...");
                    $("#progress_container").show();
                },
                uploadProgressPath: "{{MEDIA_URL}}js/jquery.uploadProgress.js",
                uploading: function(upload) {
                    if (upload.percents == 100) {
                        window.clearTimeout(this.timer);
                        $("#progress_filename").html('Processing ' + filename + "...");
                    } else {
                        $("#progress_filename").html('Uploading ' + filename + ': ' + upload.percents + '%');
                    }
                },
                interval: 1000
            });
        });
    });*/
    $("#id_rotation").after("<img id='rotation_tool' src='{{ STATIC_URL }}" +
        "pianostore/img/icon_play_video.gif'></img>");
    $("#id_rotation").hide();
    var rot_deg = 90;
    var rot_val = rot_deg;
    var rot=$('#rotation_tool').rotate({bind: [
            {"click":function(){
                rot_val = (rot_val == 360 )? 0 : rot_val;
                rot[0].rotateAnimation(rot_deg);
                var hint = $("#hint_id_rotation").html().split(":")[0];
                hint = hint + ": <b>" + rot_val + "%</b>";
                $("#id_rotation").val(rot_val);
                $("#hint_id_rotation").html(hint);
                rot_deg += 90;
                rot_val += 90;
            }},
    ]});
    $(function(){
        $('#id_date_composition').datepicker({
            dateFormat: 'yy-mm-dd',
            yearRange: '2009:2099',
            changeMonth: true,
            changeYear: true
        });
    });
    //]]>
    </script>

{% endblock %}

{% block body %}
    <h1>{% trans "Add Track" %}</h1>

    <form id="upload_form" enctype="multipart/form-data" method="POST" action="/pianostore/upload/" class="uniForm">
        {% csrf_token %}

        <div id="progress_container">
            <div id="progress_filename"></div>
            <div id="progress_bar">
                <div id="progress_indicator"></div>
            </div>
        </div>

        <fieldset class="inlineLabels">
            {{ track_form|as_uni_form }}
            <div class="form_block">
                <input type="hidden" name="upload" value="upload">
                <input type="submit" value="{% trans 'add track' %}">
            </div>
        </fieldset>
    </form>
{% endblock %}

pianostore/templates/pianostore/base.html
{% extends "site_base.html" %}
 
{% load i18n %}
 
{% block body_class %}pianostore_body{% endblock %}
 
{% block subnav %}
    <ul>
        <li><a href="{% url all_tracks %}">{% trans "All tracks" %}</a></li>
        <li><a href="{% url your_tracks %}">{% trans "Your tracks" %}</a></li>
        <li><a href="{% url add_track %}">{% trans "Add a track" %}</a></li>
    </ul>
{% endblock %}

pianostore/templates/pianostore/track.html
{% extends "pianostore/base.html" %}

{% load i18n %}
{% load uni_form_tags %}
{% load avatar_tags %}
{% load comments_tag %}

{% block head_title %}{% blocktrans %}Track Description{% endblocktrans %}{% endblock %}


{% block body %}
    <h1>{{ track.title }}</h1>
        <p>
             <div class="coverart" >
                {% if track.fullpicture %}
                    {{ track.fullpicture|safe }}
                {% else %}
                    <img src="{{ STATIC_URL }}pinax/img/silk/icons/picture_empty.png" border="0" class="noborder" align="absmiddle" />
                {% endif %}
            </div>
        </p>
        <p>
            <!-- track info -->
            <h3>{{ track.title }}</h2>
            <div class="body">
                <strong><i>{{ track.artist }}<br />{{ track.composer }}<br /></strong></i>
                            {{ track.description|linebreaks }}

                <video width="320" height="240" controls preload tabindex="0">
                    <source src="{{ MEDIA_URL }}{{ track.track_mp4 }}"
                            type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'>
                    <source src="{{ MEDIA_URL }}{{ track.track_webm }}"
                            type='video/webm; codecs="vp8, vorbis"'>
                    <source src="{{ MEDIA_URL }}{{ track.track_ogv }}"
                            type='video/ogg; codecs="theora, vorbis"'>
                        <p> {% blocktrans %}Your browser is old.{% endblocktrans %}
                            <a href="{{ MEDIA_URL }}{{ track.track_mp4 }}">
                                {% blocktrans %}Download this video instead.{% endblocktrans %}
                            </a>
                        </p>
                </video>

                {% if not track.track_mp4 %}
                    {% blocktrans %}<br />The video is currently being converted to web formats, please come back later{% endblocktrans %}
                {% endif %}
            </div>
        </p>
        <p>
            <!-- track action -->
            {% if isyours %}
                <table>
                    <tr>
                        <td>
                            <!-- udpate track -->
                            <form method="GET" action="{% url update_track track.id %}">
                                <input type="submit" value="{% trans "Update Track" %}" />
                            </form>
                        </td>
                        <td>
                            <!-- delete track -->
                            <form method="POST" action="{% url delete_track track.id %}">
                                {% csrf_token %}
                                <input type="submit" value="{% trans "Delete Track" %}" />
                            </form>
                        </td>
                    </tr>
                </table>
            {% endif %}
        </p>
        <p class="meta">
            <!-- meta -->
            <div class="avatar" >{% avatar track.adder 40 %}</div>
            <div class="details">
                {% blocktrans %}added by{% endblocktrans %}
                <a href="{% url profile_detail track.adder.username %}">{{ track.adder }}</a>
            </div>
            {% blocktrans %}on{% endblocktrans %} {{ track.date_added|date }}
            <!-- comments -->
            <h3 id="comments">{% blocktrans %}Comments on this Track{% endblocktrans %}:</h3>
            {% comments track %}
        </p>

{% endblock %}

pianostore/templates/pianostore/tracks.html
{% extends "pianostore/base.html" %}
 
{% load i18n %}
{% load avatar_tags %}
{% load pagination_tags %}
{% load threadedcommentstags %}
 
{% block head_title %}{% blocktrans %}Piano store{% endblocktrans %}{% endblock %}
 
{% block body %}
 
    <h1>
        {% ifequal list 'all' %}
            {% trans "All Tracks" %}
        {% endifequal %}
        {% ifequal list 'user' %}
            {{ username }} {% trans "tracks" %}
        {% endifequal %}
        {% ifequal list 'yours' %}
            {% trans "Your Tracks" %}
        {% endifequal %}
    </h1>
 
    <!-- alternate -->
    {% if tracks %}
    {% autopaginate tracks 5 %}

        <table class="pianostore">
            {% for track in tracks %}
            <tr class="{% if forloop.first %}odd{% else %}{% cycle even,even,odd,odd %}{% endif %}">
                    <!-- meta -->
                    <td class="meta" >
                        <div class="avatar" >{% avatar track.adder 40 %}</div>
                        <div class="details">{% blocktrans %}added by{% endblocktrans %} <a href="{% url profile_detail track.adder.username %}">{{ track.adder }}</a></div>
                        {% blocktrans %}on{% endblocktrans %} {{ track.date_added|date }}
                        <a href="/pianostore/user_tracks/{{ track.adder.username }}"><i>{% blocktrans %}View all tracks added by {% endblocktrans %}{{ track.adder }}</i></a>
                    </td>
                    <!-- track info -->
                    <td>
                        <h3><a href="/pianostore/{{ track.id }}/track/">{{ track.title }}</a></h2>
                        <div class="body">
                            <strong><i>{{ track.artist }}<br />{{ track.composer }}<br /></strong></i>
                            {{ track.description|linebreaks|truncatewords:50 }}
                        </div>
                        <!-- comments -->
                        <img src="{{ STATIC_URL }}pinax/img/silk/icons/comment.png" border="0" class="noborder" align="absmiddle" />
                            <a href="/pianostore/{{ track.id }}/track/#comments"
                                >{% get_comment_count for track as commentcount %}{{ commentcount }} Comments</a>
                            <br />
                        {% ifequal list 'yours' %}
                            <table>
                                <tr>
                                    <td>
                                        <!-- udpate track -->
                                        <form method="GET" action="{% url update_track track.id %}">
                                            <input type="submit" value="{% trans "Update Track" %}" />
                                        </form>
                                    </td>
                                    <td>
                                        <!-- delete track -->
                                        <form method="POST" action="{% url delete_track track.id %}">
                                            {% csrf_token %}
                                            <input type="submit" value="{% trans "Delete Track" %}" />
                                        </form>
                                    </td>
                                </tr>
                            </table>
                        {% endifequal %}
                    </td>
                    <!-- cover art -->
                    <td>
                        <div class="coverart" >
                            {% if track.thumb %}
                                {{ track.thumb|safe }}
                            {% else %}
                                <img src="{{ STATIC_URL }}pinax/img/silk/icons/picture_empty.png" border="0" class="noborder" align="absmiddle" />
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
 
    {% paginate %}
    {% else %}
        <p>{% trans "No tracks yet." %}</p>
    {% endif %}
 
{% endblock %}

pianostore/templates/pianostore/update.html
{% extends "pianostore/base.html" %}
 
{% load i18n %}
{% load uni_form_tags %}
 
{% block head_title %}{% blocktrans %}Add Track{% endblocktrans %}{% endblock %}
 
{% block body %}
    <h1>{% trans "Update Track: " %}{{ track.title }}</h1>
        <form enctype="multipart/form-data" method="POST" action="" class="uniForm">
            {% csrf_token %}
            <p align='center'>{{ track.fullpicture|safe }}</p>
            <fieldset class="inlineLabels">
                {{ track_form|as_uni_form }}
                <div class="form_block">
                    <input type="submit" value="{% trans 'update track' %}">
                </div>
            </fieldset>
        </form>
{% endblock %}